service:
  name: reply-bot

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10

environment:
  TWITTER_CONSUMER_KEY:
  TWITTER_CONSUMER_SECRET: a123456b
  TWITTER_ACCESS_TOKEN:
  TWITTER_ACCESS_TOKEN_SECRET:
  TWITTER_HANDLE: reply_bot

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
  crc:
    handler: handler.crc
    events:
      - http:
          method: get
          path: webhook/twitter
  listen:
    handler: handler.listen
    events:
      - http:
          method: post
          path: webhook/twitter
